# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeAlgebraicFunctions <- function(D, homDim) {
    .Call(`_TDAvec_computeAlgebraicFunctions`, D, homDim)
}

computeBettiCurve <- function(D, homDim, scaleSeq, evaluate = "intervals") {
    .Call(`_TDAvec_computeBettiCurve`, D, homDim, scaleSeq, evaluate)
}

computeComplexPolynomial <- function(D, homDim, m = 1L, polyType = "R") {
    .Call(`_TDAvec_computeComplexPolynomial`, D, homDim, m, polyType)
}

computeEulerCharacteristic <- function(D, scaleSeq, maxhomDim = -1L, evaluate = "intervals") {
    .Call(`_TDAvec_computeEulerCharacteristic`, D, scaleSeq, maxhomDim, evaluate)
}

computeLimits <- function(Dlist, homDim) {
    .Call(`_TDAvec_computeLimits`, Dlist, homDim)
}

computeNormalizedLife <- function(D, homDim, scaleSeq, evaluate = "intervals") {
    .Call(`_TDAvec_computeNormalizedLife`, D, homDim, scaleSeq, evaluate)
}

computePersistenceBlock <- function(D, homDim, xSeq, ySeq, tau = 0.3) {
    .Call(`_TDAvec_computePersistenceBlock`, D, homDim, xSeq, ySeq, tau)
}

computePersistenceImage <- function(D, homDim, xSeq, ySeq, sigma) {
    .Call(`_TDAvec_computePersistenceImage`, D, homDim, xSeq, ySeq, sigma)
}

computePersistenceLandscape <- function(D, homDim, scaleSeq, k = 1L, generalized = FALSE, kernel = "triangle", h = NULL) {
    .Call(`_TDAvec_computePersistenceLandscape`, D, homDim, scaleSeq, k, generalized, kernel, h)
}

computePersistenceSilhouette <- function(D, homDim, scaleSeq, p = 1.0, evaluate = "intervals") {
    .Call(`_TDAvec_computePersistenceSilhouette`, D, homDim, scaleSeq, p, evaluate)
}

computePersistentEntropy <- function(D, homDim, scaleSeq, evaluate = "intervals") {
    .Call(`_TDAvec_computePersistentEntropy`, D, homDim, scaleSeq, evaluate)
}

computeStats <- function(D, homDim) {
    .Call(`_TDAvec_computeStats`, D, homDim)
}

computeTemplateFunction <- function(D, homDim, delta, d, epsilon) {
    .Call(`_TDAvec_computeTemplateFunction`, D, homDim, delta, d, epsilon)
}

computeTropicalCoordinates <- function(D, homDim, r = 1L) {
    .Call(`_TDAvec_computeTropicalCoordinates`, D, homDim, r)
}

