# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeAF <- function(D, homDim) {
    .Call(`_TDAvec_computeAF`, D, homDim)
}

computeBetti <- function(D, homDim, scaleSeq, evaluate = "intervals") {
    .Call(`_TDAvec_computeBetti`, D, homDim, scaleSeq, evaluate)
}

computeCP <- function(D, homDim, m = 1L, polyType = "R") {
    .Call(`_TDAvec_computeCP`, D, homDim, m, polyType)
}

computeECC <- function(D, scaleSeq, maxhomDim = -1L, evaluate = "intervals") {
    .Call(`_TDAvec_computeECC`, D, scaleSeq, maxhomDim, evaluate)
}

computeLimits <- function(Dlist, homDim) {
    .Call(`_TDAvec_computeLimits`, Dlist, homDim)
}

computeNL <- function(D, homDim, scaleSeq, evaluate = "intervals") {
    .Call(`_TDAvec_computeNL`, D, homDim, scaleSeq, evaluate)
}

computePES <- function(D, homDim, scaleSeq, evaluate = "intervals") {
    .Call(`_TDAvec_computePES`, D, homDim, scaleSeq, evaluate)
}

computePI <- function(D, homDim, xSeq, ySeq, sigma) {
    .Call(`_TDAvec_computePI`, D, homDim, xSeq, ySeq, sigma)
}

computePL <- function(D, homDim, scaleSeq, k = 1L, generalized = FALSE, kernel = "triangle", h = NULL) {
    .Call(`_TDAvec_computePL`, D, homDim, scaleSeq, k, generalized, kernel, h)
}

computePS <- function(D, homDim, scaleSeq, p = 1.0, evaluate = "intervals") {
    .Call(`_TDAvec_computePS`, D, homDim, scaleSeq, p, evaluate)
}

computeStats <- function(D, homDim) {
    .Call(`_TDAvec_computeStats`, D, homDim)
}

computeTC <- function(D, homDim, r = 1L) {
    .Call(`_TDAvec_computeTC`, D, homDim, r)
}

computeTF <- function(D, homDim, delta, d, epsilon) {
    .Call(`_TDAvec_computeTF`, D, homDim, delta, d, epsilon)
}

computeVPB <- function(D, homDim, xSeq, ySeq, tau = 0.3) {
    .Call(`_TDAvec_computeVPB`, D, homDim, xSeq, ySeq, tau)
}

